{% set version = "0.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-precommit
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/precommit_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/precommit/precommit_{{ version }}.tar.gz
  sha256: 95b51ee58a4a52d7278852b6cb0c74b529e3b1439e03338b1fe9351277afdd21

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r.cache
    - r-cli
    - r-fs
    - r-here
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-rprojroot
    - r-rstudioapi
    - r-withr
    - r-yaml
  run:
    - r-base
    - r-r.cache
    - r-cli
    - r-fs
    - r-here
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-rprojroot
    - r-rstudioapi
    - r-withr
    - r-yaml

test:
  commands:
    - $R -e "library('precommit')"           # [not win]
    - "\"%R%\" -e \"library('precommit')\""  # [win]

about:
  home: https://lorenzwalthert.github.io/precommit/, https://github.com/lorenzwalthert/precommit
  license: GPL-3.0-or-later
  summary: Useful git hooks for R building on top of the multi-language framework 'pre-commit' for hook management. This package provides git hooks for common tasks like formatting files with 'styler' or spell checking as well as wrapper functions to access the 'pre-commit' executable.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - lorenzwalthert
